name: test
on: [push]
jobs:
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest]
  runs-on: ${{ matrix.os }}
  steps: 
    - uses: actions/checkout@v3
    - name: make
      run: make hello
    - name: run
      run: ./hello